name: bittrex_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  tuple: ^1.0.3
  #Dependency Injections
  kiwi: ^0.2.0
  provider: ^4.0.4
  #State managementsy
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  #routing
  fluro: ^1.6.3
  #UI libraries
  shimmer: ^1.1.1
  oktoast: ^2.3.1+1
  get_version: ^0.2.2
  device_info: ^0.4.2+1
  app_settings: ^3.0.1
  # The following adds the Cupertino Icons font to your appx  lication.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #Storage
  flutter_secure_storage:
    path: ../../../flutter_secure_storage
  shared_preferences: ^0.5.6+3
  #Utils
  path_provider: ^1.6.5
  sprintf: ^4.0.2
  platform: ^2.2.1
  #http + ws
  http: ^0.12.0+4
  dio: ^3.0.9
  permission_handler: ^5.0.0+hotfix.3
  rxdart: ^0.20.0
  # image util
  image_picker: ^0.6.5
  flutter_advanced_networkimage:
    git:
      url: https://github.com/mchome/flutter_advanced_networkimage.git
      ref: 3688a8177d94b8e324b16dfeb01f70c5a6c83d59
#  image_downloader: ^0.15.4
  multi_image_picker: ^4.6.5+rc.1
  #image processing
#  image: ^2.1.12
#  image_crop:
#    git:
#      url: https://github.com/thesoftwarefanatics/image_crop.git
#      ref: 650631b0c76ae07820bc7c2d61317cb73d70c6a7
  # Push Notify
  flutter_local_notifications: ^1.4.1
  firebase_messaging:
    git:
      url: https://github.com/VuongDo92/flutterfire.git
      path: packages/firebase_messaging
  firebase_core: ^0.4.4+3
  url_launcher: ^5.4.2
  flutter_custom_tabs: ^0.6.0
  intl: any

  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.1
  firebase_storage: ^3.1.5

dev_dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation:
  flutter_test:
    sdk: flutter
module:
  androidX: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/3x/
    - assets/images/2x/
    - assets/locale/
#    - packages/time_machine/data/cultures/cultures.bin
#    - packages/time_machine/data/tzdb/tzdb.bin

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          style: normal
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 200
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages